spring.application.name=furima-a
spring.datasource.url=jdbc:postgresql://localhost:5432/furima_development
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Thymeleaf設定
spring.thymeleaf.cache=false
git status
# Flyway設定
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration