spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/proto_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true
spring.flyway.enabled=true
file.upload-dir=./uploads
# 修正例（サイズを指定する場合）
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# server.servlet.session.cookie.secure=false
server.port=8080
# ローカル環境(http://localhost)で安全にCookieを扱える設定に変更
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.http-only=true